# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            Cooking Apps
tagline:          'Sergio Plata&#39;s Blog'
description:      'Sergio Plata | Mobile & Web Developer'
url:              http://splata.github.io/
baseurl:          /
logo:             /assets/images/logo.png

author:
  name:           'Sergio Plata'
  url:            https://twitter.com/cooking_apps

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/splata/splata.github.io

gems:
  - jekyll-sitemap
  - jekyll-paginate

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
  future: true