# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CookingApps
tagline:          'Sergio Plata&#39;s Blog'
description:      'Sergio Plata | Mobile Developer'
url:              http://splata.github.io/
baseurl:          /

author:
  name:           'Sergio Plata'
  url:            https://twitter.com/cooking_apps

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false