# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cooking Apps
tagline:          'Sergio Plata&#39;s Blog'
description:      'Sergio Plata | Mobile developer'
url:              http://splata.github.io/
baseurl:          /

author:
  name:           'Sergio Plata'
  url:            https://twitter.com/cooking_apps

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
